# Generated by Django 4.2.25 on 2026-03-03 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, max_length=255)),
                ('commit_message', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('ai_provider', models.CharField(blank=True, max_length=100)),
                ('ai_model', models.CharField(blank=True, max_length=255)),
                ('raw_response', models.TextField(blank=True)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('schema_changes', models.JSONField(default=list)),
                ('data_changes', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('affected_db_objects', models.JSONField(default=list)),
                ('affected_code_objects', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='analyses/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('script_type', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sql_content', models.TextField()),
                ('table', models.CharField(blank=True, max_length=255)),
                ('is_breaking', models.BooleanField(default=False)),
                ('sql_file', models.FileField(blank=True, null=True, upload_to='analyses/scripts/')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='analyzer_ui.analysis')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['sequence'],
            },
        ),
    ]
